Algoritmo "03_Exercicio_Senha_Fixa"
// Disciplina   : [Curso Udemy - Algoritmos e Lógica de Programação]
// Professor   : Nelio Alves
// Autor(a)    : HenriqueJRodrigues
Var

   senha: inteiro

Inicio

   escreva("Digite a senha:")
   leia(senha)
   
    enquanto senha <> 2002 faça
     escreva("Senha Inválida! Tente novamente: ")
      leia(senha)
    fimenquanto
    
    escreva("Acesso permitido! ")
     
Fimalgoritmo